
RANDOM_REPLIES = [

    "МІША ВСЬО ХУЙНЯ ДАВАЙ СНАЧАЛА",

    "іді в пізду",

    "я щас вам палку в анус засуну",

    "не переступайте за рамки, це вже не смішно",

    "чорті-шо і збоку бантік",

"LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT LESTAT",

]

